// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <AMAZEPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(AMAZE,Engine)

// ****************************************************************************
//  Method: AMAZEEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a AMAZE writer.
//
//  Returns:    A AMAZE writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
AMAZEEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

